spring:
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:h2:file:./social-media-db/social-media-db;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true